### ISSUE TITLE
Unable to run in Colab

### ISSUE THREAD

**Issue by ahianf** [tg-bomze/BabyGAN#15]
I've tried with lot of images, even with the original Kim and Kanye pictures but with no success. As with #10 and #12 I noticed 
finetuned_resnet.h5 missing from Drive, and I fixed that, but still throws this traceback.

```
Using TensorFlow backend.
WARNING:tensorflow:From <string>:364: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2022-03-19 07:27:36.295828: W tensorflow/core/common_runtime/bfc_allocator.cc:305] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2022-03-19 07:27:36.594422: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.16GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2022-03-19 07:27:38.223780: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
  0% 0/1 [00:00<?, ?it/s]WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/keras/backend/tensorflow_backend.py:431: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/keras/backend/tensorflow_backend.py:438: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

Loading mask masks/father_01.png
Loading mask masks/mother_01.png
Loading ResNet Model:

  0% 0/100 [00:00<?, ?it/s]WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/math_grad.py:281: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().

  0% 0/1 [00:40<?, ?it/s]
Traceback (most recent call last):
  File "encode_images.py", line 242, in <module>
    main()
  File "encode_images.py", line 176, in main
    for loss_dict in pbar:
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/content/BabyGAN/encoder/perceptual_model.py", line 291, in optimize
    min_op = optimizer.minimize(self.loss, var_list=[vars_to_optimize])
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/contrib/optimizer_v2/optimizer_v2.py", line 724, in minimize
    grads_and_vars, global_step=global_step, name=name)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/contrib/optimizer_v2/optimizer_v2.py", line 879, in apply_gradients
    kwargs={"global_step": global_step, "name": name})
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/distribute/distribute_lib.py", line 1940, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/distribute/distribute_lib.py", line 1947, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/contrib/optimizer_v2/optimizer_v2.py", line 938, in _distributed_apply
    self._create_vars(var_list, state)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/contrib/opt/python/training/ggt.py", line 143, in _create_vars
    [window, idx], dtype=var_list[0].dtype.base_dtype)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py", line 2338, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 3052, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (GGT/window:0) to a numpy array.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-8e574cbe69ad> in <module>()
     19 with dnnlib.util.open_url(URL_FFHQ, cache_dir=config.cache_dir) as f:
     20     generator_network, discriminator_network, Gs_network = pickle.load(f)
---> 21 generator = Generator(Gs_network, batch_size=1, randomize_noise=False)
     22 model_scale = int(2*(math.log(1024,2)-1))
     23 

8 frames
/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    866         tb = [x for x in tb if "tensorflow/python" not in x[0]][:5]
    867         raise ValueError("%s Originally defined at:\n\n%s" %
--> 868                          (err_msg, "".join(traceback.format_list(tb))))
    869       found_var = self._vars[name]
    870       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable learnable_dlatents already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
```

**Comment by 595972434** [comment]
I met same error

**Comment by georgymh** [comment]
According to [this thread](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy), all you need to do is force-use `numpy` version `1.19.5`.

So by adding

```
!pip install 'numpy==1.19.5'
```

on the first cell before the other pip install, the notebook works.

**Comment by ahianf** [comment]
> According to [this thread](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy), all you need to do is force-use `numpy` version `1.19.5`.
> 
> So by adding
> 
> ```
> !pip install 'numpy==1.19.5'
> ```
> 
> on the first cell before the other pip install, the notebook works.

Thanks it does work now.
